name: Run tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn
      - name: Run unit tests
        run: yarn test
      - name: Run integration tests on Ethereum fork
        run: yarn test:int-eth
      - name: Run integration tests on Arbitrum fork
        run: yarn test:int-arb
